templates.resourceCollectionTpl = _.template([
    '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<div class="row">',
                '<div class="col-md-6">',
                    '<h4>Resources</h4>',
                '</div>',
                '<div class="col-md-4">',
                    '<input type="text" class="form-control searchField" autofocus placeholder="Search">',
                '</div>',
                '<div class="col-md-2">',
                    '<button class="btn btn-success pull-right create">',
                        '<i class="glyphicon glyphicon-plus-sign"></i> Add',
                    '</button>',
                '</div>',
            '</div>',
        '</div>',
        '<table class="table resource-list" onmousedown="return false">',
            '<tr>',
                '<th class="name-header">Name<i class="sort-flag glyphicon glyphicon-sort glyphicon-triangle-bottom"></i></th>',
                '<th class="type-header">Type<i class="sort-flag glyphicon glyphicon-sort"></i></th>',
                '<th>Use in schedule</th>',
            '</tr>',
        '</table>',
    '</div>',
    '<nav>',
    '</nav>'
].join(''));