templates.userSettingsTpl = _.template([
    '<div class="modal-backdrop fade in"></div>',
	'<div id="mymodal1" class="userSettingsView modal-dialog animated slideInDown">',
		'<div class="modal-content">',
			'<div class="modal-header">',
			    '<button type="button" class="close cancel"><span aria-hidden="true">&times;</span></button>',
				'<h4 class="modal-title">Edit account</h4>',
			'</div>',
			'<div class="modal-body clearfix">',
				'<div class="accountForm">',
					'<div class="row">',
						'<div class="col-md-6">',
							'<div class="form-group" class="col-xs-4">',
								'<label for="InputName">Enter Name</label>',
								'<input type="text" class="name form-control tabIndex" value="<%= name %>" name="name" id="InputName" placeholder="Enter Name" readonly>',
							'</div>',
							'<div class="form-group" class="col-xs-4">',
								'<label for="InputLastName">Enter Lastname</label>',
								'<input type="text" class="form-control tabIndex" value="<%= lastName %>" name="lastName" id="InputlastName" placeholder="Enter lastName" readonly>',
							'</div>',
							'<div class="form-group loginForm">',
								'<label for="InputLogin">Enter Login:</label>',
								'<input type="text" class="form-control tabIndex" value="<%= login %>" name="login" id="InputLogin" placeholder="Enter Login" readonly>',
							'</div>',
							'<div class="form-group">',
								'<label for="InputPassword">Enter Password</label>',
								'<div id="psswordWrong" class="input-group" data-toggle="tooltip" data-placement="top">',
									'<input type="text" class="form-control password-input tabIndex" value="<%= password %>" name="password" id="InputPassword" placeholder="Genarate password">',
									'<span class="input-group-btn">',
										'<button class="btn btn-default generate-pass tabIndex" type="button">Generate</button>',
									'</span>',
								'</div>',
							'</div>',
						'</div>',
						'<div class="col-md-6">',
							'<div class="row">',
								'<div class="img-preview">',
									'<span class="glyphicon glyphicon-user"></span>',
									'<img class="preview" src="<%= avatar %>">',
								'</div>',
								'<div>',
									'<button class="load-photo btn btn-default load-photo tabIndex" onclick="this.nextSibling.click()">Select a file</button>',
									'<input type="file" class="user-avatar" style="visibility: hidden"/>',
								'</div>',
							'</div>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="modal-footer">',
				'<button id="save" type="button" class="btn btn-info save pull-right tabIndex">',
					'<i class="glyphicon glyphicon-floppy-saved"></i> Save',
				'</button>',
			'</div>',
		'</div>',
	'</div>'
].join(''));  