templates.weekPreviewTpl = _.template([
'        <tr>',
'        <td><input type="button" class="back" value="Back"></td>',    
'        </tr>',    
'        <tr>',
'        <td class="groups">',
'            Groups',
'        </td>',
'        <% resources.forEach(function (resource) { %>',
'           <% if (resource.type === 0) { %>',
'               <td class="<%= resource.id %> resource">',
'                   <%= resource.name %>',
'               </td>',
'           <% } %>',
'        <% }); %>',
'        </tr>',
'        <tr>',
'        <td class="Teachers">',
'            Teachers',
'        </td>',
'        <% resources.forEach(function (resource) { %>',
'           <% if (resource.type === 2) { %>',
'               <td class="<%= resource.id %> resource">',
'                   <%= resource.name %>',
'               </td>',
'           <% } %>',
'        <% }); %>',
'        </tr>',
'        <tr>',
'        <td class="Rooms">',
'            Rooms',
'        </td>',
'        <% resources.forEach(function (resource) { %>',
'           <% if (resource.type === 1) { %>',
'               <td class="<%= resource.id %> resource">',
'                   <%= resource.name %>',
'               </td>',
'           <% } %>',
'        <% }); %>',
'        </tr>'
].join(''));