'use strict';
templates.accountCollectionTpl = _.template([
        '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<div class="row">',
                '<div class="col-md-9 col-sm-8">',
                    '<h4>Accounts <i class="glyphicon glyphicon-user"></i></h4>',
                '</div>',
                '<div class="col-md-3 col-sm-4">',
                    '<button class="btn btn-success pull-right create">',
                        '<i class="glyphicon glyphicon-plus-sign"></i> Add',
                    '</button>',
                '</div>',
            '</div>',
        '</div>',
        '<table class="table account-list" onmousedown="return false">',
            '<tr>',
                '<th class="name-header">Name<i class="sort-flag glyphicon glyphicon glyphicon-sort glyphicon-triangle-bottom"></th>',
                '<th class="login-header">Login<i class="sort-flag glyphicon glyphicon glyphicon-sort"></th>',
                '<th class="location-header">Location<i class="sort-flag glyphicon glyphicon glyphicon-sort"></th>',
                '<th class="role-header">Role</th>',
            '</tr>',
        '</table>',
    '</div>'].join(''));