templates.createAccountTpl = _.template([
   '<div class="modal-backdrop fade in"></div>',
	'<div class="modal-dialog animated slideInDown myAnimateClass">',
		'<div class="modal-content">',
			'<div class="modal-header">',
				'<button type="button" class="close cancel"><span aria-hidden="true">&times;</span></button>',
				 '<h4 class="modal-title"><%= (name === "")? "Create account": "Edit account" %></h4>',
			'</div>',
			'<div class="modal-body clearfix">',
				'<div class="accountForm">',
					'<div class="row">',
						'<div class="col-md-6">',
							'<div class="form-group" class="col-xs-4">',
								'<label for="InputName">First Name</label>',
								'<span class="hint hidden"></span>',
								'<input type="text" class="name form-control tabIndex" value="<%= name %>" name="name" id="InputName" placeholder="Enter Name" autofocus>',
							'</div>',
							'<div class="form-group" class="col-xs-4">',
								'<label for="InputLastName">Last Name</label>',
								'<span class="hint hidden"></span>',
								'<input type="text" class="form-control tabIndex" value="<%= lastName %>" name="lastName" id="InputlastName" placeholder="Enter LastName">',
							'</div>',
							'<div class="form-group loginForm">',
								'<label for="InputLogin">Login</label>',
								'<span class="hint hidden"></span>',
								'<input type="text" class="form-control tabIndex" value="<%= login %>" name="login" id="InputLogin" placeholder="Enter Login">',
								'<a class="returnLogin tabIndex">Return my variant</a>',
							'</div>',
						'</div>',
						'<div class="col-md-6">',
							'<div class="row">',
								'<div class="img-preview">',
									'<span class="glyphicon glyphicon-user">',
									'</span>',
									'<img class="preview" src="<%= avatar %>">',
								'</div>',
								'<div>',
									'<button class="load-photo btn btn-default" onclick="this.nextSibling.click()">Select a file</button>',
									'<input type="file" name="avatar" class="user-avatar" accept="image/jpeg,image/png" style="visibility: hidden"/>',
								'</div>',
							'</div>',
						'</div>',
					'</div>',
					'<div class="form-group" class="col-xs-4">',
						'<label for="InputPassword">Password</label>',
                        '<div class="input-group">',
                        '<span class="hint hidden"></span>',
                            '<input type="text" class="form-control password-input" value="<%= password %>" name="password" id="InputPassword" placeholder="Genarate password" readonly>',
                            '<span class="input-group-btn">',
                                '<button class="btn btn-default generate-pass form-control tabIndex" name="password" type="button">Generate</button>',
                            '</span>',
                        '</div>',
					'</div>',
					'<div class="form-group">',
						'<label for="locationCity">Select City</label>',
						'<span class="hint hidden"></span>',
						'<select class="form-control listbox tabIndex" name="locationCity" id="locationCity">',
							'<% if (city) { %>',
								'<option selected value="<%= city.id %>">',
									'<%= city.get("name") %>',
								'</option>',
							'<% } else {%>',
								'<option value="" default disabled selected>Select city</option>',
							'<% }%>',                            
							'<% _.each(locationCity, function (city) {%>',
								'<option value="<%= city.id %>">',
									'<%= city.name %>',
								'</option>',
							'<% }) %>',
						'</select>',
					'</div>',
					'<div class="form-group">',
						'<label for="role">Select Role</label>',
						'<select class="form-control" name="role" id="role">',
						'<% if (role) { %>',
							'<option value="<%= role %>"><%= role %></option>',
							'<% if (role === "Admin") { %>',
								'<option value="Coordinator">Coordinator</option>',
							'<% } else {%>',
								'<option value="Admin">Admin</option>',
							'<% }%>',
						'<% } else {%>',
							'<option value="Coordinator">Coordinator</option>',
							'<option value="Admin">Admin</option>',
						'<% }%>',
						'</select>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="modal-footer">',
				'<button id="save" type="button" class="btn btn-info save pull-right tabIndex">',
					'<i class="glyphicon glyphicon-floppy-saved"></i> Save',
				'</button>',
				'<button type="button" class="btn btn-default cancel pull-left tabIndex">',
					'<i class="glyphicon glyphicon-floppy-remove"></i> Back',
				'</button>',
			'</div>',
		'</div>',
	'</div>'
].join(''));  