templates.cascadeDeleteTpl = _.template([
    '<div class="modal-backdrop fade in"></div>',
        '<div class="modal-dialog modal-md confirm-dialog">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<h4 class="modal-title"><%= message %> </h4>',
                '</div>',
                '<button type="button" class="btn btn-warning btn-block" data-toggle="collapse" data-target="#demo">Relations: <span class="badge"><%= relations.length %></span></button>',
                '<div id="demo" class="collapse">',
                    '<div>',
                        '<ul>',
                        '<% _.each(relations, function (item) { %>',
                            '<li>',
                                '<%= item %>',
                            '</li>',
                        '<% }); %>',
                        '</ul>',
                    '</div>',
                '</div>',
                '<div class="modal-body clearfix">',
                    '<div class="btn-toolbar pull-right">',
                        '<button type="button" class="btn btn-default delete">Yes</button>',
                        '<button type="button" class="btn btn-default cancel">No</button>',
                    '</div>',
                '</div>',
            '</div>',
        '</div>',
    '</div>'
].join(''));