templates.daysRowTpl = _.template([
'	<tr>',
'		<td class="cell chooseWeek">',
'		</td>',
'		<% dayNumber = 1%>',
'		<td class="cell chooseDay"  attribute = <%= dayNumber++%>>',
'			Monday',
'		</td>',
'		<td class="cell chooseDay" attribute = <%= dayNumber++%>>',
'			Tuesday',
'		</td>',
'		<td class="cell chooseDay" attribute = <%= dayNumber++%>>',
'			Wednesday',
'		</td>',
'		<td class="cell chooseDay" attribute = <%= dayNumber++%>>',
'			Thursday',
'		</td>',
'		<td class="cell chooseDay" attribute = <%= dayNumber++%>>',
'			Friday',
'		</td>',
'		<td class="cell" attribute = <%= dayNumber++%>>',
'			Saturday',
'		</td>',
'		<td class="cell" attribute = 0>',
'			Sunday',
'		</td>',
'	</tr>',
'	<tr>',
'		<td class="cell chooseWeek"></td>',
'		<td class="cell">',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell" choseDay = "">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell" choseDay = "">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell" choseDay = "">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell" choseDay = "">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell" choseDay = "">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'		<td class="cell" choseDay = "">',
'			<% startDate.setDate(startDate.getDate() + 1)  %>',
'			<%= startDate.getDate() + "." + +(startDate.getMonth() + 1) %>',
'		</td>',
'	</tr>'].join(''));