templates.calendarRowTpl = _.template([
'	<tr  timeline = "<%= timeline %>">',
'		<td class="cell chooseTimeline" attribute = <%= timeline %>>',
'			<%= timeline %>',
'			<a name= "<%= timeline %>"></a>',
'		</td>',
'		<td class="calendarCell" day= "<%= day %>" timeline = "<%= timeline %>">',
'		</td>',
'		<td class="calendarCell" day= "<%= day = day + 1 %>" timeline = "<%= timeline %>">',
'		</td>',
'		<td class="calendarCell" day= "<%= day = day + 1 %>" timeline = "<%= timeline %>">',
'		</td>',
'		<td class="calendarCell" day= "<%= day = day + 1 %>" timeline = "<%= timeline %>">',
'		</td>',
'		<td class="calendarCell" day= "<%= day = day + 1 %>" timeline = "<%= timeline %>">',
'		</td>',
'		<td class="calendarCell" day= "<%= day = day + 1 %>" timeline = "<%= timeline %>">',
'		</td>',
'		<td class="calendarCell" day= "<%= day = 0 %>" timeline = "<%= timeline %>">',
'		</td>',
'	</tr>'].join(''));