templates.scheduleEventsTpl = _.template([
'	<div class="row">',
'		<div class="col-md-4"></div>',
'		<div class="col-md-8">',
'			<div class="schedulePager"></div>',
'		</div>',
'	</div>',
'	<div class="row">',
'		<div class="col-md-4">',
'			<div class = "scheduleEvents"></div>',
'			<div class = "conflict"></div>',
'			<div class = "weekMode"></div>',
'		</div>',
'		<div class="col-md-8">',
'			<div class = "Myschedule"></div>',
'		</div>',
'	</div>',
'	<div class="row">',
'		<div class="col-md-4">',
'			<div class = "download"></div>',
'		</div>',
'		<div class="col-md-4">',
'		</div>',
'		<div class="col-md-4">',
'			<div class = "clone"></div>',
'		</div>',
'	</div>'].join(''));